//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataTools.Import.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDataTools.Import.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH [Tables] AS(
        ///	SELECT
        ///		&apos;[&apos; + [schemas].[name] + &apos;].[&apos; + [tables].[name] + &apos;]&apos;  AS[TableName]
        ///		, [tables].[object_id] AS[TableId]
        ///		, [schemas].[name] AS[Schema]
        ///		, [tables].[name] AS [Table]
        ///	FROM [sys].[schemas]
        ///	INNER JOIN [sys].[tables]
        ///		ON [tables].[schema_id] = [schemas].[schema_id]
        ///), [ForeignKeys]
        ///AS(
        ///	SELECT
        ///		[Parent].[Schema] AS[ParentSchemaName],
        ///		[Parent].[Table] AS[ParentTableName],
        ///		&apos;[&apos; + [foreign_keys].[name] + &apos;]&apos; AS[ForeignKey],
        ///		[Parent].[TableName] AS[Parent],
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BeforeAfterScripts {
            get {
                return ResourceManager.GetString("BeforeAfterScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH [Tables] AS(
        ///	SELECT
        ///		&apos;[&apos; + [schemas].[name] + &apos;].[&apos; + [tables].[name] + &apos;]&apos;  AS[TableName]
        ///		, [tables].[object_id] AS[TableId]
        ///		, [schemas].[name] AS[Schema]
        ///		, [tables].[name] AS [Table]
        ///	FROM [sys].[schemas]
        ///	INNER JOIN [sys].[tables]
        ///		ON [tables].[schema_id] = [schemas].[schema_id]
        ///), [Columns] AS (
        ///	SELECT 
        ///		 [columns].[object_id]
        ///		 ,[columns].[name] AS [ColumnName]
        ///		 ,[columns].[column_id] AS [ColumnOrder]
        ///		 --,&apos;JSON_VALUE(@json, &apos;&apos;$[0].&apos;+ [columns].[name] +&apos;&apos;&apos;) AS [&apos;+[colu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuildMerge {
            get {
                return ResourceManager.GetString("BuildMerge", resourceCulture);
            }
        }
    }
}
